import dynamic from 'next/dynamic';

export const components = {
  Background: dynamic(() => import('./Background')),
  BannerVideo: dynamic(() => import('./BannerVideo')),
  Button: dynamic(() => import('./Button')),
  Description: dynamic(() => import('./Description')),
  Pagination: dynamic(() => import('./Pagination')),
  Icon: dynamic(() => import('./Icon')),
  Image: dynamic(() => import('./Image')),
  Link: dynamic(() => import('./Link')),
  Text: dynamic(() => import('./Text')),
  InputText: dynamic(() => import('./InputText')),
  Navigation: dynamic(() => import('./Navigation')),
  Dropdown: dynamic(() => import('./Dropdown')),
  Collapse: dynamic(() => import('./Collapse')),
  InputSearch: dynamic(() => import('./InputSearch')),
  Tabs: dynamic(() => import('./Tabs')),
  Table: dynamic(() => import('./Table')),
  LoginForm: dynamic(() => import('./LoginForm')),
  ListDrivers: dynamic(() => import('./ListDrivers')),
  CustomWidget3d7a58493472: dynamic(() => import("./CustomWidget3d7a58493472")),
  CustomWidgeta44b59665e03: dynamic(() => import("./CustomWidgeta44b59665e03")),
  CustomWidgeta5c07b174292: dynamic(() => import("./CustomWidgeta5c07b174292")),
};
